### PR TITLE
HWKALERTS-148 - Fixed the response for missing tenant header.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
A response in JSON format is the expected in Metrics and Alerts. @metlos is this also OK for Inventory?

**Comment by jpkrohling** [comment]
@tsegismont , @jshaughn , could you also please take a look at this PR ?

**Comment by metlos** [comment]
Yep, inventory uses the same class for error reporting..

**Comment by tsegismont** [comment]
LGTM

**Pull request merged**
