### PR TITLE
Merge repo h*inv*-model into h*inv*-api under package "model"

### PR DESCRIPTION
**Pull request by jotak**
Also put rest tests under package "handlers" instead of "service"

### CODE REVIEW

**Comment by lucasponce** [comment]
+1
I will merge when tests are green.

**Comment by jotak** [comment]
NOTE: #152 should be merged first, then this one rebased

**Comment by lucasponce** [comment]
#152 merged, do you need to manually rebase this one ?

**Comment by lucasponce** [comment]
LGTM

**Pull request merged**
