### PR TITLE
CORS Support

### PR DESCRIPTION
**Pull request by jshaughn**
- Add allowed methods
- change property name from hawkular.cors-url to hawkular.cors-origin-pattern
  - this better reflects what the value actually is. It is a pattern and supports
    this like, .*localhost:.*

I carried over the defaults we used in the jaxrs cors support module
in commons.

### CODE REVIEW

**Comment by jshaughn** [comment]
@lucasponce or @jmazzitelli please review.

**Comment by jmazzitelli** [comment]
much nicer. obviously, we need to fix hawkular.properties and perhaps other places in hawkular-alerting due to this change here.

**Comment by jshaughn** [comment]
Yes, assuming this goes in we can update the properties file and the commons src-dep.

**Comment by lucasponce** [comment]
LGTM

**Pull request merged**
