### PR TITLE
HAWKULAR-1089 - Removed embedded Cassandra

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@pilhuhn , could you please review/merge? Once it's merged, I'll release commons so that it can be incorporated early by other components.

**Comment by pilhuhn** [comment]
Completely removing it from hawkular-commons seems to be wrong.
We must not include it in hawkular-services, but may still want to include it in a hawkular-full distribution

**Comment by jpkrohling** [comment]
Then hawkular-full would have to re-add this then, IMO. The nest is the base for our distribution, so, if we don't want Cassandra at the intermediate distribution, we shouldn't have it at the basic building block.

**Comment by jpkrohling** [comment]
Or did you mean that we should keep the maven module `embedded-cassandra` ? If so, then I agree that we could keep it.

**Comment by pilhuhn** [comment]
I think I meant the maven module :)

**Comment by jpkrohling** [comment]
Ok, we could keep it here, or we could maintain it at the hawkular-all level. I'm not sure I like this module here in Commons, as it implies that other components are free to use it, like any other commons module.

We could decide on that later, though.

**Comment by jpkrohling** [comment]
@pilhuhn : ready for re-review

**Comment by jpkrohling** [comment]
I'll change this PR to have the integration tests to use embedded Cassandra.

**Comment by jpkrohling** [comment]
Updated the commit to use embedded Cassandra on itests.

**Comment by jpkrohling** [comment]
Reviewed via IRC.

**Pull request merged**
