### PR TITLE
Ignore Eclipse project files

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@stefannegrea could you please review and eventually merge?

**Comment by pilhuhn** [comment]
Would you mind adding the respective IDEA files as well? Or perhaps just take a .gitignore from another project?

**Comment by ppalaga** [comment]
@pilhuhn a good idea. I will.

**Comment by ppalaga** [comment]
@pilhuhn  `.gitignore` entries in 408338e are from Hawkular

**Pull request merged**
