### PR TITLE
CORS filter allow empty allowed origins

### PR DESCRIPTION
**Pull request by pavolloffay**
@jpkrohling could you please review?

### CODE REVIEW

**Comment by pavolloffay** [comment]
@jshaughn @stefannegrea Could you please review too?

**Comment by jshaughn** [comment]
It's not totally clear to me what value we get from a null/empty CORS filter, but this seems fine for handling the situation.  What is the use case?  If it is to protect against a bad setting perhaps we  should log a warning.

**Comment by pavolloffay** [comment]
Basically, it is to protect against a bad setting. When null was passed it threw NPE, when `""` was passed it threw NPE later in a path evaluation, so this PR should protect against these two errors.

**Comment by jpkrohling** [comment]
Looks good to me.

**Pull request merged**
