### PR TITLE
Allow sending an explicit close using TestWebSocketClient

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

**Comment by jpkrohling** [comment]
Is it only a change in the tests? No need to change the actual counterpart for these socket connections?

**Comment by jpkrohling** [comment]
If so, looks good to me.

**Comment by ppalaga** [comment]
> No need to change the actual counterpart for these socket connections?

Let's see what it does like this. We upgraded okhttp, so hopefully setting explicit timeouts there will be enough.

**Pull request merged**
