### PR TITLE
Upgrade to Cassandra 3.4 via hawkular-parent 40

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

Parent 40 only upgrades to Cassandra 3.4. The upgrade to Cassandra 3.4 was agreed on with @jsanda .

**Comment by jpkrohling** [comment]
Failed on Travis?

**Comment by ppalaga** [comment]
hm... heap space in EAR plugin - that happens randomly from time to time

**Comment by ppalaga** [comment]
@jpkrohling Passed after enough retries.

**Pull request merged**
